apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: id-09-test
    cloudkyc.com/tier: backend
  name: id-09-test
  namespace: cloudkyc-services
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: id-09-test
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: id-09-test
    cloudkyc.com/tier: backend
  name: id-09-test
  namespace: cloudkyc-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: id-09-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: id-09-test
        cloudkyc.com/tier: backend
      namespace: cloudkyc-services
    spec:
      serviceAccountName: 209-test
      containers:
        - name: id-09-test
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: eu.gcr.io/cloud-kyc/209-test
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 45
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
